'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {toast} from 'sonner';
import {type Action,when,EmptyState} from './app-shared';
import {type ViewData,type Order,type Withdrawal,usdt,inr,UNIT} from '@/lib/types';
const labels={requested:'Awaiting admin',sending:'Manual transfer in progress',submitted:'TRON confirmation pending',completed:'Transfer verified',cancelled:'Cancelled'};
export function ManualDeliveryTerms({data}:{data:ViewData}){
 const s=data.settlement;
 return <div className="inline-notice manual-terms"><div><strong>Manual USDT delivery · TRC20 only</strong><p>Payment goes to DivinePay. Wallet credit requires verified payment and admin approval; a QR or UTR submission alone does not credit USDT. Withdrawals are sent manually by the operator.</p>{s?<><p>Delivery target: within {s.deliveryHours} hours after a withdrawal request.</p><p>Refunds / delayed delivery: {s.refundPolicy}</p><p>Support: {s.supportContact}</p></>:<p>The operator has not completed the sending-wallet and delivery terms setup. Do not pay.</p>}{!data.gateway.enabled&&<p>{data.gateway.reason}</p>}</div></div>;
}
export function AdminPaymentApproval({order,data,act,busy}:{order:Order;data:ViewData;act:Action;busy:boolean}){
 const [note,setNote]=useState(''),[confirm,setConfirm]=useState(false);
 if(order.approval)return <div className="inline-notice">Payment approved {when(order.approval.at)}. {usdt(order.quantity,6)} USDT was credited once. External delivery is tracked under Withdrawals.</div>;
 return <section className="panel"><h2>Payment review & approval</h2><p>{inr(order.fiat)} · {usdt(order.quantity,6)} USDT</p><p className="muted">Check the existing payment in the gateway dashboard. This action independently verifies the provider order and amount before crediting the customer. Screenshots, UTR entry or an admin click alone are not payment proof.</p>{!order.liveEligible&&<div className="form-error">This legacy order has no funded manual-delivery checkout. Reconcile any existing payment before collecting again.</div>}<form className="form-stack" onSubmit={async e=>{e.preventDefault();if(await act({action:'approve_payment',orderId:order.id,note,confirm})){setNote('');setConfirm(false);toast.success('Verified payment approved. USDT credited once.');}}}><label>Gateway review note<Textarea required minLength={8} maxLength={500} value={note} onChange={e=>setNote(e.target.value)} placeholder="Payment checked in the gateway dashboard"/></label><label className="consent-row"><Checkbox checked={confirm} onCheckedChange={v=>setConfirm(v===true)}/>I checked this payment and accept responsibility for delivering the credited USDT.</label><Button disabled={busy||!confirm||note.trim().length<8||!order.liveEligible||!order.payment?.providerOrderId||!data.gateway.creditEnabled} type="submit">Verify payment & approve USDT</Button></form></section>;
}
export function SettlementWallet({data,act,busy}:{data:ViewData;act:Action;busy:boolean}){
 const [recipient,setRecipient]=useState(''),[amount,setAmount]=useState(''),[confirm,setConfirm]=useState(false),[requestId,setRequestId]=useState(()=>crypto.randomUUID());
 const wallet=data.user?.live||{available:0,locked:0},quantity=Math.round(Number(amount)*UNIT);
 const history=data.ledger.filter(l=>l.real);
 async function request(e:React.FormEvent){e.preventDefault();if(await act({action:'request_withdrawal',recipient,quantity,network:'TRC20',requestId,confirm})){setRequestId(crypto.randomUUID());setAmount('');setRecipient('');setConfirm(false);toast.success('Withdrawal requested. USDT is locked until the manual transfer is verified.');}}
 return <><div className="page-heading"><div><span className="eyebrow">VERIFIED PURCHASE BALANCE</span><h1>My wallet</h1></div></div><div className="wallet-hero"><div><p>Platform USDT balance</p><h2>{usdt(wallet.available+wallet.locked,6)} <span>USDT</span></h2><p>Only verified, admin-approved purchases. Historical sample balances are excluded.</p><Button asChild><a href="/">Buy USDT</a></Button></div><div className="wallet-split"><div><span>Available to request</span><strong>{usdt(wallet.available,6)} USDT</strong></div><div><span>Locked for withdrawal</span><strong>{usdt(wallet.locked,6)} USDT</strong></div></div></div><ManualDeliveryTerms data={data}/><section className="panel"><h2>Withdraw USDT · TRC20</h2><form className="form-stack" onSubmit={request}><label>Amount (USDT)<Input required type="number" min="0.000001" max={wallet.available/UNIT} step="0.000001" value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal"/></label><label>Receiving wallet address<Input required maxLength={34} minLength={34} value={recipient} onChange={e=>setRecipient(e.target.value.trim())} autoComplete="off" autoCapitalize="none" spellCheck={false} placeholder="Your TRON address, starting with T"/></label><Button type="button" variant="outline" onClick={async()=>{try{setRecipient((await navigator.clipboard.readText()).trim());}catch{toast.info('Tap and hold the address field and choose Paste.');}}}>Paste wallet address</Button><label className="consent-row"><Checkbox checked={confirm} onCheckedChange={v=>setConfirm(v===true)}/>I checked this receiving address and it accepts USDT on TRC20 (TRON).</label><p className="muted">The requested amount is locked, not sent automatically. Admin sends the exact amount manually. It leaves your total balance only after the matching transfer is verified on TRON. Do not request a replacement while a transfer is in progress.</p><Button disabled={busy||!confirm||!data.gateway.senderConfigured||!Number.isSafeInteger(quantity)||quantity<=0||quantity>wallet.available} type="submit">Request withdrawal</Button></form></section><div className="section-heading"><h2>Withdrawal requests</h2></div>{data.withdrawals.length?data.withdrawals.map(w=><WithdrawalCard key={w.id} withdrawal={w} act={act} busy={busy}/>):<EmptyState title="No withdrawal requests" text="Your requests and verified transfer references will appear here."/>}<section className="panel"><h2>Verified transaction history</h2>{history.length?history.map(l=><div className="settlement-history-row" key={l.id}><div><strong>{l.type}</strong><p>{l.orderId} · {when(l.time)}</p></div><strong>{l.amount>0?'+':''}{usdt(l.amount,6)} USDT</strong></div>):<p className="muted">No approved purchases or completed withdrawals yet.</p>}</section></>;
}
function WithdrawalCard({withdrawal:w,act,busy,admin=false,data}:{withdrawal:Withdrawal;act:Action;busy:boolean;admin?:boolean;data?:ViewData}){
 const [txHash,setTxHash]=useState(''),[confirm,setConfirm]=useState(false);
 async function perform(action:string,extra:Record<string,unknown>={}){if(await act({action,withdrawalId:w.id,...extra}))toast.success(action==='verify_transfer'?'TRC20 transfer verified. Balance deducted once.':'Withdrawal record updated.');}
 return <section className="panel withdrawal-card"><div className="section-heading"><div><h2>{usdt(w.quantity,6)} USDT</h2><p>{w.id} · {labels[w.phase]}</p></div><span className="small-pill">TRC20</span></div>{admin&&<p>Customer: {data?.users.find(u=>u.id===w.user)?.name||w.user}</p>}<dl><div><dt>Receiving address</dt><dd className="break-address">{w.recipient}</dd></div><div><dt>Sending address</dt><dd className="break-address">{w.sender}</dd></div><div><dt>Requested</dt><dd>{when(w.created)}</dd></div></dl>{w.txHash&&<p className="break-address">Transaction: <a href={'https://tronscan.org/#/transaction/'+w.txHash} target="_blank" rel="noreferrer">{w.txHash}</a></p>}{w.phase==='completed'&&<div className="inline-notice">Transfer verified on TRON. {usdt(w.quantity,6)} USDT has been deducted from the locked balance.</div>}{w.phase==='requested'&&<div className="button-row">{admin&&<Button disabled={busy} onClick={()=>void perform('start_withdrawal',{confirm:true})}>Start manual transfer</Button>}<Button disabled={busy} variant="outline" onClick={()=>void perform('cancel_withdrawal')}>Cancel unstarted request</Button></div>}{admin&&w.phase==='sending'&&<form className="form-stack" onSubmit={e=>{e.preventDefault();void perform('record_transfer',{txHash});}}><div className="inline-notice">Send exactly {usdt(w.quantity,6)} USDT from the sending address above to the receiving address on TRC20. This app does not send it for you. Check the wallet history first; never send twice.</div><label>Existing transfer transaction ID<Input required pattern="[a-fA-F0-9]{64}" maxLength={64} value={txHash} onChange={e=>setTxHash(e.target.value.trim())}/></label><label className="consent-row"><Checkbox checked={confirm} onCheckedChange={v=>setConfirm(v===true)}/>I have sent this transfer and am recording its existing transaction ID.</label><Button disabled={busy||!confirm||txHash.length!==64} type="submit">Record transaction ID</Button></form>}{w.phase==='submitted'&&<><p className="muted">The amount remains locked until this exact transaction is confirmed. If it is pending or verification fails, check the same transaction—do not send again.</p>{admin&&<Button disabled={busy} onClick={()=>void perform('verify_transfer')}>Verify on TRON & complete</Button>}</>}</section>;
}
export function AdminWithdrawals({data,act,busy}:{data:ViewData;act:Action;busy:boolean}){
 return data.withdrawals.length?<>{data.withdrawals.map(w=><WithdrawalCard key={w.id} withdrawal={w} data={data} act={act} busy={busy} admin/>)}</>:<EmptyState title="No withdrawals to process" text="Customer requests appear here after a verified purchase is approved and the customer submits a TRC20 address."/>;
}
export function ManualSettlementSettings({data,act,busy}:{data:ViewData;act:Action;busy:boolean}){
 const s=data.settlement;const [sender,setSender]=useState(s?.senderAddress||''),[hours,setHours]=useState(String(s?.deliveryHours||'')),[refund,setRefund]=useState(s?.refundPolicy||''),[contact,setContact]=useState(s?.supportContact||''),[control,setControl]=useState(false),[reserve,setReserve]=useState<number|null>(null);
 return <form className="settings-form panel form-stack" onSubmit={async e=>{e.preventDefault();const result=await act({action:'manual_settings',senderAddress:sender,deliveryHours:Number(hours),refundPolicy:refund,supportContact:contact,confirmControl:control});if(result){setReserve(result.result?.reserveUsdt??null);toast.success('Manual delivery settings saved.');}}}><h2>Manual USDT delivery · TRC20</h2><p className="muted">Only public wallet information belongs here. Never enter a private key or seed phrase. Saving settings does not enable live payments by itself; the server payment switch must also be enabled.</p><label>Admin sending wallet address<Input required value={sender} onChange={e=>setSender(e.target.value.trim())} minLength={34} maxLength={34} placeholder="Public TRON address starting with T"/></label><label>Manual delivery target (hours)<Input required type="number" min="1" max="168" value={hours} onChange={e=>setHours(e.target.value)}/></label><label>Refund / delayed-delivery policy shown before payment<Textarea required minLength={30} maxLength={1200} value={refund} onChange={e=>setRefund(e.target.value)} placeholder="Explain the genuine refund and delayed-delivery process"/></label><label>Customer support email or contact<Input required minLength={5} maxLength={120} value={contact} onChange={e=>setContact(e.target.value)}/></label><label className="consent-row"><Checkbox checked={control} onCheckedChange={v=>setControl(v===true)}/>I control this sending wallet, will fund all customer obligations, and will manually deliver genuine USDT under these terms.</label><p className="muted">The server checks the real TRC20 USDT balance before creating a payment or approving credit. Listing inventory and historical sample balances do not count as reserves.</p>{reserve!==null&&<div className="inline-notice">Observed on-chain reserve: {reserve} USDT. This is a point-in-time balance, not a custody guarantee.</div>}<Button disabled={busy||!control} type="submit">Check wallet & save delivery setup</Button></form>;
}
