'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {type Action} from './demo-shared';
import {UNIT,type ViewData,type Offer} from '@/lib/demo-types';
import {toast} from 'sonner';
export function OfferEditor({open,onClose,act,busy,offer}:{open:boolean;onClose:()=>void;data:ViewData;act:Action;busy:boolean;admin?:boolean;offer?:Offer|null}){
 const [name,setName]=useState(offer?.displayName||''),[price,setPrice]=useState(String(offer?offer.price/100:98)),[quantity,setQuantity]=useState(String(offer?offer.available/UNIT:10000)),[min,setMin]=useState(String((offer?.min||500000)/100)),[max,setMax]=useState(String((offer?.max||3000000)/100));
 async function save(e:React.FormEvent){e.preventDefault();const result=await act({action:'offer',...(offer?{id:offer.id}:{}),displayName:name,side:'sell',price:Math.round(Number(price)*100),available:Math.round(Number(quantity)*UNIT),min:Math.round(Number(min)*100),max:Math.round(Number(max)*100),methods:['UPI']});if(result){toast.success(offer?'Seller updated in Buy USDT':'Seller registered — visible in Buy USDT');onClose();}}
 return <Dialog open={open} onOpenChange={value=>!value&&!busy&&onClose()}><DialogContent className="trade-dialog" showCloseButton={!busy}><DialogHeader><DialogTitle>{offer?'Edit seller':'Register seller'}</DialogTitle><DialogDescription>Customers will see this seller in P2P → Buy USDT. Set the seller’s name, rate, available quantity and purchase limits.</DialogDescription></DialogHeader><form className="form-stack" onSubmit={save}><fieldset className="form-stack" disabled={busy}><label>Seller name<Input required minLength={2} maxLength={50} placeholder="Seller name shown in P2P" value={name} onChange={e=>setName(e.target.value)}/></label><div className="form-grid"><label>Price per USDT (INR)<Input required type="number" inputMode="decimal" min="1" max="1000" step=".01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Available quantity (test USDT)<Input required type="number" inputMode="decimal" min="1" max="100000" step=".000001" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Minimum purchase (INR)<Input required type="number" inputMode="decimal" min="5000" max="30000" step=".01" value={min} onChange={e=>setMin(e.target.value)}/></label><label>Maximum purchase (INR)<Input required type="number" inputMode="decimal" min={Math.max(5000,Number(min)||5000)} max="30000" step=".01" value={max} onChange={e=>setMax(e.target.value)}/></label></div><div className="rate-presets"><span>Quick rate</span>{[96,98].map(rate=><Button key={rate} type="button" variant="outline" size="sm" onClick={()=>setPrice(String(rate))}>₹{rate}</Button>)}</div><div className="inline-notice">Customer action: Buy USDT · Payment: UPI<br/>Purchase limits must stay within ₹5,000–₹30,000.</div><p className="muted">This registers a local seller listing, not a paid transaction. Existing orders keep their original price and quantity.</p><Button disabled={busy} type="submit">{busy?'Saving…':offer?'Save seller details':'Register seller & show in Buy'}</Button></fieldset></form></DialogContent></Dialog>;
}
