'use client';
import {useState} from 'react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Search,Download,ChevronRight} from 'lucide-react';
import {FilterTabs,Status,EmptyState,when,csvDownload} from './app-shared';
import {inr,usdt,type ViewData,type Order} from '@/lib/types';
export function OrderList({data,admin=false,onlyDisputed=false,compact=false}:{data:ViewData;admin?:boolean;onlyDisputed?:boolean;compact?:boolean}){
 const [filter,setFilter]=useState('all'),[q,setQ]=useState('');const name=(id:string)=>data.users.find(u=>u.id===id)?.name||id;
 const rows=data.orders.filter(o=>(!onlyDisputed||o.status==='disputed')&&(filter==='all'||(filter==='active'?!['completed','cancelled'].includes(o.status):o.status===filter))&&[o.id,name(o.buyer),name(o.seller)].join(' ').toLowerCase().includes(q.toLowerCase())).slice(0,compact?6:1000);
 function exportRows(){csvDownload('nexa-orders.csv',['Order ID','Buyer','Seller','USDT','Rate INR','Amount INR','Fee USDT','Status','Created by','Created UTC'],rows.map(o=>[o.id,name(o.buyer),name(o.seller),o.quantity/1e6,o.price/100,o.fiat/100,o.fee/1e6,o.status,o.createdBy==='admin'?'Admin':name(o.createdBy||o.buyer),new Date(o.created).toISOString()]));}
 return <div className="records-panel">{!compact&&<><div className="records-toolbar"><div className="search-box"><Search size={17}/><Input placeholder="Search order or trader" aria-label="Search orders" value={q} onChange={e=>setQ(e.target.value)}/></div><Button variant="outline" onClick={exportRows}><Download size={16}/>Export CSV</Button></div>{!onlyDisputed&&<FilterTabs value={filter} onChange={setFilter} items={[[ 'all','All orders'],['active','In progress'],['completed','Completed'],['cancelled','Cancelled']]}/>}</>}{rows.length?<Table className="records-table"><TableHeader><TableRow><TableHead>Order / Time</TableHead><TableHead>{admin?'Buyer / Seller':'Trade'}</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead><TableHead/></TableRow></TableHeader><TableBody>{rows.map(o=><TableRow key={o.id}><TableCell><strong>{o.id}</strong><small>{when(o.created)}</small>{o.createdBy==='admin'&&<span className="order-origin">Admin created</span>}</TableCell><TableCell>{admin?<><strong>{name(o.buyer)}</strong><small>from {name(o.seller)}</small></>:<><strong className={o.buyer===data.user?.id?'teal':'rose'}>{o.buyer===data.user?.id?'Buy':'Sell'} USDT</strong><small>{name(o.buyer===data.user?.id?o.seller:o.buyer)}</small></>}</TableCell><TableCell><strong>{inr(o.fiat)}</strong><small>{usdt(o.quantity,4)} USDT</small></TableCell><TableCell><Status value={o.status}/></TableCell><TableCell><Button asChild variant="ghost" size="sm"><a href={(admin?'/admin/orders/':'/orders/')+o.id}>View<ChevronRight size={14}/></a></Button></TableCell></TableRow>)}</TableBody></Table>:<EmptyState title="No orders here yet" text={q?'Try a different search.':'Your trades will appear here with their status and details.'}><Button asChild variant="outline"><a href="/">Find a trade</a></Button></EmptyState>}</div>;
}
