export const UNIT=1_000_000;
export type User={id:string;name:string;email:string;mobile?:string;referralCode?:string;referredBy?:string|null;accountType?:'registered'|'listing';created?:number;available:number;locked:number;kyc:'verified'|'pending';blocked:boolean;merchant:boolean;orders:number;completion:number;payment:string};
export type Offer={id:string;owner:string;side:'buy'|'sell';price:number;available:number;min:number;max:number;methods:string[];minutes:number;active:boolean;terms:string;createdBy?:'admin';displayName?:string;updated?:number};
export type OrderStatus='awaiting_payment'|'paid'|'disputed'|'completed'|'cancelled';
export type GatewayPayment={phase:'creating'|'pending'|'unknown'|'failed'|'review';providerOrderId?:string;checkoutUrl?:string;updated:number};
export type Message={id:string;sender:string;text:string;time:number};
export type Order={id:string;offerId:string;buyer:string;seller:string;quantity:number;fee:number;price:number;fiat:number;method:string;status:OrderStatus;created:number;expires:number;updated:number;messages:Message[];reason:string;createdBy?:string;createdFor?:string;requestId?:string;requestFingerprint?:string;paymentMode?:'gateway_pending';advertiserName?:string;payment?:GatewayPayment};
export type Ledger={id:string;user:string;type:string;amount:number;orderId:string;time:number;reference:string};
export type Audit={id:string;actor:string;action:string;target:string;time:number};
export type Settings={brand:string;announcement:string;trading:boolean;feeBps:number;orderMinutes:number};
export type AppState={users:User[];offers:Offer[];orders:Order[];ledger:Ledger[];audit:Audit[];settings:Settings;treasury:number};
export type ViewData={user:User|null;role:'user'|'admin'|'guest';users:User[];offers:Offer[];orders:Order[];ledger:Ledger[];audit:Audit[];settings:Settings;treasury:number;revision:number;registrationCode?:string;gateway:{configured:boolean;enabled:boolean;creditEnabled:false;reason:string}};
export const number=(n:number,d=2)=>new Intl.NumberFormat('en-IN',{minimumFractionDigits:d,maximumFractionDigits:d}).format(n);
export const usdt=(n:number,d=2)=>number(n/UNIT,d);
export const inr=(n:number)=>'₹'+number(n/100);
export const statusLabel=(s:string)=>({awaiting_payment:'Awaiting payment',paid:'Payment marked',disputed:'In dispute',completed:'Completed',cancelled:'Cancelled'}[s]||s);
